name:self-supervised learning
channel:
  - conda-forge
  - defaults
dependencies:
python == 3.9.20
scipy.spatial
numpy<2.0
pythonocc-core
pytorch
torch_scatter
torch_geometric
scikit-learn
occwl
jupyter
